version: 2
updates:
  - package-ecosystem: "poetry"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "04:00"
    groups:
      poetry-packages:
        patterns:
          - "*"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "Deps:"
